# ==========================================
# WiMANS-CLIP 极简配置文件
# ==========================================

# 1. 数据管道参数 (严格遵循 WiMANS 原生过滤条件)
data:
  video_dir: "/media/a123456/6109数据集存放/WiMANS_Dataset/dataset/video"
  wifi_dir: "/media/a123456/6109数据集存放/WiMANS_Dataset/dataset/wifi_csi/amp"
  annotation_file: "/media/a123456/6109数据集存放/WiMANS_Dataset/dataset/annotation.csv"
  
  # 数据集过滤 (控制参与训练的数据分布)
  #
  environments: ["classroom"] # "classroom", "meeting_room", "empty_room"
  num_users: ["0", "1", "2", "3", "4", "5"] #"0", "1", "2", "3", "4", "5"
  wifi_band: ["5"] 

# 2. 网络架构参数
model:
  video_backbone: "S3D"  # 视觉基线模型
  wifi_backbone: "THAT"     # WiFi 基线模型
  wifi_length: 3000         # WiFi 强制对齐的时间步长 (原生标准)
  
  # 跨模态对齐维度
  projection_dim: 512
  init_temperature: 0.07

# 3. 训练与评估参数
train:
  seed: 39                  # 固定的随机种子
  batch_size: 16
  accumulation_steps: 1
  learning_rate: 0.004
  epochs: 100
  num_workers: 4
  # 保存在同级目录 result 中
  save_dir: "../result/clip"
  save_top_k: 5             # 保留指标最好的 3 个模型

test:
  # 测试时去 result 文件夹读取你指定的具体模型
  weight_path: "../result/clip/ago/7单用户三个场景/clip_epoch_83_v2w_0.4230_w2v_0.4678.pth"
  linear_probe_epochs: 100
  batch_size: 32
  num_workers: 4
